[tools]
go = "latest"
node = "latest"
npm = "latest"
python = "3.14"
pipx = "latest"
uv = "latest"
ruby = "latest"
rust = "latest"
sbcl = "latest"
cargo-binstall = "latest"
"cargo:eza" = { version = "latest", depends = "cargo-binstall" }
"cargo:sheldon" = { version = "latest", depends = "cargo-binstall" }
"cargo:starship" = { version = "latest", depends = "cargo-binstall" }
"cargo:zoxide" = { version = "latest", depends = "cargo-binstall" }
"cargo:du-dust" = { version = "latest", depends = "cargo-binstall" }
"cargo:bat" = { version = "latest", depends = "cargo-binstall" }
"cargo:fd-find" = { version = "latest", depends = "cargo-binstall" }
"cargo:ripgrep" = { version = "latest", depends = "cargo-binstall" }
"cargo:git-delta" = { version = "latest", depends = "cargo-binstall" }
gping = "latest"
"cargo:bottom" = { version = "latest", depends = "cargo-binstall" }
"cargo:tlrc" = { version = "latest", depends = "cargo-binstall" }
"cargo:choose" = { version = "latest", depends = "cargo-binstall" }
"cargo:procs" = { version = "latest", depends = "cargo-binstall" }
"cargo:sd" = { version = "latest", depends = "cargo-binstall" }
"cargo:tre" = { version = "latest", depends = "cargo-binstall" }
"cargo:xh" = { version = "latest", depends = "cargo-binstall" }
"cargo:difftastic" = { version = "latest", depends = "cargo-binstall" }
"cargo:yazi-fm" = { version = "latest", depends = "cargo-binstall" }
"cargo:duf" = { version = "latest", depends = "cargo-binstall" }
"cargo:macchina" = { version = "latest", depends = "cargo-binstall" }
"cargo:riffdiff" = { version = "latest", depends = "cargo-binstall" }
"cargo:grex" = { version = "latest", depends = "cargo-binstall" }
"cargo:aichat" = { version = "latest", depends = "cargo-binstall" }
"cargo:intelli-shell" = { version = "latest", depends = "cargo-binstall" }
"cargo:lowcharts" = { version = "latest", depends = "cargo-binstall" }
"cargo:wachikun/yaskkserv2" = { version = "latest", depends = "cargo-binstall" }
"cargo:termusic" = { version = "latest", depends = "cargo-binstall" }
"cargo:termusic-server" = { version = "latest", depends = "cargo-binstall" }
"cargo:broot" = { version = "latest", depends = "cargo-binstall" }
"cargo:cookcli" = { version = "latest", depends = "cargo-binstall" }
peco = "latest"
doggo = "latest"
cheat = "latest"
curlie = "latest"
lazygit = "latest"
fx = "latest"
bitwarden = "latest"
fzf = "latest"
yj = "latest"
age = "latest"
"aqua:gokcehan/lf" = "latest"
"aqua:zquestz/s" = "latest"
"aqua:sibprogrammer/xq" = "latest"
"aqua:Boeing/config-file-validator" = "2.1.0"
"aqua:awslabs/git-secrets" = "latest"
"github:s0rg/crawley" = "latest"
"github:Hakky54/certificate-ripper" = "latest"
"github:Achno/gowall" = "latest"
"github:akavel/up" = "latest"
"github:slavaGanzin/await" = "latest"
"github:marph91/jimmy" = "latest"
"github:Qalculate/libqalculate" = "latest"
"github:browsh-org/browsh" = "1.8.2"
"github:jdx/usage" = "latest"
"go:github.com/bnagy/cgasm" = "latest"
"pipx:ruff" = { version = "latest", depends = "uv" }
"pipx:glances" = { version = "latest", depends = "uv" }
"pipx:howdoi" = { version = "latest", depends = "uv" }
"pipx:yewtube" = { version = "latest", depends = "uv" }
# "pipx:radio-active" = { version = { version = "latest", depends = "uv" }, pipx_args = ["--python", "~/.local/share/mise/installs/python/3.13.x/bin/python3.13"] }
"pipx:moviemon" = { version = "latest", depends = "uv" }
"pipx:epy-reader" = { version = "latest", depends = "uv" }
"pipx:rebound-cli" = { version = "latest", depends = "uv" }
"pipx:buku" = { version = "latest", depends = "uv" }
"pipx:hns" = { version = "latest", depends = "uv" }
"pipx:lakshmi" = { version = "latest", depends = "uv" }
"pipx:gcalcli" = { version = "latest", depends = "uv" }
"pipx:deadlink" = { version = "latest", depends = "uv" }
"pipx:thefuck" = { version = "latest", depends = "uv" }
"pipx:recoverpy" = { version = "latest", depends = "uv" }
"pipx:ricksay" = { version = "latest", depends = "uv" }
"pipx:marker" = { version = "latest", depends = "uv" }
"pipx:pdd" = { version = "latest", depends = "uv" }
"pipx:pywal" = { version = "latest", depends = "uv" }
"npm:prettier" = { version = "latest", depends = "npm" }
"npm:bible" = { version = "latest", depends = "npm" }
"npm:birthday" = { version = "latest", depends = "npm" }
"npm:themer" = { version = "latest", depends = "npm" }
"npm:mdlt" = { version = "latest", depends = "npm" }
"npm:hget" = { version = "latest", depends = "npm" }
"npm:trino" = { version = "latest", depends = "npm" }
"npm:emoj" = { version = "latest", depends = "npm" }
"gem:vj" = "latest"
"gem:boom" = "latest"
